// src/components/home/HabitsList.tsx
import Modal from "@components/Modal";
import { Habit, habitsData } from "@data/habits";
import { useStore } from "@nanostores/react";
import { habits, toggleModal } from "@stores/habits";

function HabitsList() {
  const $habits = useStore(habits);
  const filteredHabits = habitsData.filter(
    (habitData) => !$habits.find((habit) => habitData.id === habit.id)
  );

  return (
    <section className="grid w-full grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-4">
      {filteredHabits.map((habit) => (
        <Card habit={habit} key={habit.id} />
      ))}
      <Modal />
    </section>
  );
}

function Card({ habit }: { habit: Habit }) {
  return (
    <button
      className="btn h-24 flex-col border-none bg-base-200 normal-case"
      onClick={() => toggleModal(habit)}
    >
      <span className="flex grow items-center text-lg">{habit.icon}</span>
      <h2 className="flex grow items-start text-center">{habit.name}</h2>
    </button>
  );
}

export default HabitsList;

// src/components/app/HabitsList.svelte
<script lang="ts">
  import { habitsData } from "@data/habits";
  import { habits, toggleModal } from "@stores/habits";

  $: filteredHabits = habitsData.filter(
    (habitData) => !$habits.some((habit) => habitData.id === habit.id)
  );
</script>

<section class="grid w-full grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-4">
  {#each filteredHabits as habit}
    <button
      class={`btn h-24 flex-col border-none normal-case`}
     
      data-cy={habit.name}
      on:click={() => toggleModal(habit)}
    >
      <span class="flex grow items-center text-lg">{habit.icon}</span>
      <h2 class="flex grow items-start text-center">{habit.name}</h2>
    </button>
  {/each}
</section>
