// src/components/modal/ModalForm.tsx
import type { HabitData } from "@data/habits";
import { toggleModal, addHabit, deleteHabit, habits } from "@stores/habits";
import React, { useState } from "react";
import { useStore } from "@nanostores/react";
import { Inputs } from "./Inputs";
import type { InputCategory } from "@data/inputs";

function ModalForm({ habit }: { habit: HabitData }) {
  const [state, setState] = useState<HabitData>(habit);
  const $habits = useStore(habits);

  // Check if the current item exists in the added habits
  const isPresent = $habits.some((habit) => habit.id === state.id);

  function handleSubmit(e: React.FormEvent<HTMLFormElement>, habit: HabitData) {
    e.preventDefault();

    // FIXME: Find a better way to handle this bug
    // Small timeout to prevent seeing the modal changing content
    setTimeout(() => addHabit({ ...habit, ...state }), 200);
    toggleModal();
  }

  function handleForm(
    e: React.ChangeEvent<HTMLSelectElement | HTMLInputElement>,
    category: InputCategory
  ) {
    const { name, value } = e.target;
    setState((habit) => ({
      ...habit,
      inputs: habit.inputs.map((input) => {
        console.log(name, input.inputCategory);

        return input.inputCategory === category
          ? { ...input, [name]: value }
          : input;
      }),
    }));
  }

  return (
    <form onSubmit={(e) => handleSubmit(e, habit)}>
      {state.inputs.map((input) => (
        <Inputs key={input.name} handler={handleForm} input={input} />
      ))}
      <div className="modal-action">
        {isPresent ? (
          <>
            <RemoveButton habit={habit} />
            <UpdateButton />
          </>
        ) : (
          <>
            <CancelButton />
            <AddButton />
          </>
        )}
      </div>
    </form>
  );
}

function AddButton() {
  return (
    <button className="btn-primary btn grow" type="submit">
      Add Habit
    </button>
  );
}

function UpdateButton() {
  return (
    <button className="btn-success btn grow" type="submit">
      Update
    </button>
  );
}

function RemoveButton({ habit }: { habit: HabitData }) {
  return (
    <button
      type="button"
      className="btn-ghost btn grow text-error"
      onClick={() => {
        toggleModal(), deleteHabit(habit);
      }}
    >
      Remove
    </button>
  );
}

function CancelButton() {
  return (
    <button
      type="button"
      className="btn-ghost btn grow"
      onClick={() => toggleModal()}
    >
      Cancel
    </button>
  );
}

export default ModalForm;

// src/components/modal/ModalForm.svelte
<script lang="ts">
  import ModalInputs from "./ModalInputs.svelte";

  import type { Habit } from "@data/habits";
  import { toggleModal, addHabit, deleteHabit, habits } from "@stores/habits";

  // Check if the current item exists in the added habits
  $: isPresent = $habits.some((habit) => habit.id === state.id);
  export let habit: Habit;
  let state = habit;
  function handleSubmit(habit: Habit) {
    // FIXME: Find a better way to handle this bug
    // Small timeout to prevent seeing the modal changing content
    setTimeout(() => addHabit({ ...habit, ...state }), 200);
    toggleModal();
  }
</script>

<form on:submit|preventDefault={() => handleSubmit(habit)}>
  <ModalInputs {habit} />
  <div class="modal-action">
    {#if isPresent}
      <button
        type="button"
        class="btn-ghost btn grow text-error"
        on:click={() => {
          toggleModal(), deleteHabit(habit);
        }}
        data-cy={"remove-btn"}
      >
        Remove
      </button>
      <button class="btn-success btn grow" type="submit" data-cy={"btn-update"}>
        Update
      </button>
    {:else}
      <button
        type="button"
        class="btn-ghost btn grow"
        on:click={() => toggleModal()}
        data-cy={"cancel-btn"}
      >
        Cancel
      </button>
      <button class="btn-primary btn grow" type="submit" data-cy={"btn-submit"}>
        Add Habit
      </button>
    {/if}
  </div>
</form>
