// src/components/HabitCard.tsx
import { useStore } from "@nanostores/react";
import type { Habit } from "@data/habits";
import { habits, toggleModal } from "@stores/habits";
import Modal from "./Modal";

interface Props {
  habit: Habit;
}

function HabitCard({ habit }: Props) {
  const $habits = useStore(habits);

  return (
    <>
      <button
        className="card flex h-24 items-center justify-center bg-base-300 p-4 transition-colors hover:bg-base-200"
        onClick={toggleModal}
      >
        <span className="flex basis-full items-center text-lg">
          {habit.icon}
        </span>
        <h2 className="flex basis-full items-start text-center">
          {habit.name}
        </h2>
      </button>
      <Modal habit={habit} />
    </>
  );
}
export default HabitCard;

// src/components/habit/HabitCard.svelte
<script lang="ts">
  import type { Habit } from "@data/habits";
  import { currentHabit, modal } from "src/stores";
  import {
    generateFunComparaison,
    transformToObj,
    createFormatter,
  } from "@util/index";
  import { slide } from "svelte/transition";

  const gradients = [
    "bg-gradient-to-r from-sky-400 to-blue-500",
    "bg-gradient-to-r from-emerald-500 to-lime-600",
    "bg-gradient-to-r from-red-500 to-red-800",
    "bg-gradient-to-r from-orange-600 to-orange-500",
  ];

  export let year: number;
  export let index: number;
  export let habit: Habit;
  let inputs = transformToObj(habit.inputs);
  let { time, frequency, liquid, generic } = inputs;
  $: inputs = transformToObj(habit.inputs);
  $: {
    ({ time, frequency, liquid, generic } = inputs);
  }
</script>

<button
  class="card no-animation cursor-pointer gap-1 p-4 {gradients[
    index % 4
  ]} w-full"
  on:click={() => {
    currentHabit.set(habit), modal.toggleOpen();
  }}
  in:slide={{ duration: 200 }}
  data-cy="{habit.name}-grid-card"
>
  <div class="flex items-center gap-2 text-xl font-bold uppercase">
    <span class="text-base">{habit.icon}</span>
    <p class="text-sm text-base-300/80">{habit.name}</p>
  </div>

  <p class="text-3xl font-bold text-base-300">
    {#if time && frequency}
      {createFormatter({
        frequency: frequency.selectedOption,
        dailyValue: Number(time.value),
        unit: time.selectedOption,
        year,
      }).hoursPerYear}
    {:else if liquid}
      {createFormatter({
        dailyValue: Number(liquid.value),
        unit: liquid.selectedOption,
        year,
      }).liquidPerYear}
    {:else if generic}
      {createFormatter({
        dailyValue: Number(generic.value),
        year,
      }).hoursPerYear}
      {generic.options[0] && generic.options[0][1]}
    {/if}
  </p>

  <p class="text-start text-sm text-base-300">
    {generateFunComparaison(habit, inputs, year)}
  </p>
</button>
